import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import FitMyTruckApp from "./App";

describe("FitMyTruckApp", () => {
  it("renders the primary mobile MVP choices", () => {
    const html = renderToString(<FitMyTruckApp />);
    expect(html).toContain("Build My Workday");
    expect(html).toContain("Build My Play Day");
    expect(html).toContain("Map My Day");
    expect(html).toContain("Find My Truck");
    expect(html).toContain("FleetFit");
  });

  it("keeps Find My Truck out of the primary pill row and shows a bottom search card instead", () => {
    const html = renderToString(<FitMyTruckApp />);
    const nav = html.match(/<nav aria-label="Primary"[^>]*>[\s\S]*?<\/nav>/)?.[0] ?? "";
    expect(nav).toContain("Build My Workday");
    expect(nav).toContain("Build My Play Day");
    expect(nav).toContain("Map My Day");
    expect(nav).toContain("FleetFit");
    expect(nav).not.toContain("Find My Truck");
    expect(html).toContain("find-fits-cta");
    expect(html).toContain("find-truck-cta");
    expect(html).toContain("See What Fits This Workday");
  });

  it("renders the Phase 1 Workday Fit assessment journey", () => {
    const html = renderToString(<FitMyTruckApp />);
    expect(html).toContain("Electrical");
    expect(html).toContain("Pool Service");
    expect(html).toContain("Landscaping / Lawn");
    expect(html).toContain("Property Maintenance / Handyman");
    expect(html).toContain("Construction / Remodel");
    expect(html).toContain("Type your trade");
    expect(html).not.toContain("Battery-Powered Lawn / Landscaping");
    expect(html).not.toContain("Locksmith");
    expect(html).not.toContain("More trades");
    expect(html).toContain("Number of stops");
    expect(html).toContain("Overflow trailer");
    expect(html).toContain("16-ft open");
    expect(html).toContain("12-ft enclosed");
    expect(html).toContain("10-ft enclosed");
    expect(html).toContain("Trade kit on the truck");
    expect(html).toContain("Select the ones that apply.");
    expect(html).toContain("Type IA extension");
    expect(html).toContain("Working wire");
    expect(html).toContain("Additional 300 lb miscellaneous");
    expect(html).toContain("Additional 500 lb miscellaneous");
    expect(html).not.toContain("12V cooler");
    expect(html).toContain("Bed accessories");
    expect(html).toContain("Select all that apply.");
    expect(html).toContain("Bed drawers / slide-out storage");
    expect(html).toContain("27-gal totes");
    expect(html).toContain("Soft tri-fold tonneau");
    expect(html).toContain("Hard folding tonneau");
    expect(html).toContain("Ladder / commercial rack");
    expect(html).toContain("Headache rack");
    expect(html).toContain("Crossbed toolbox");
    expect(html).toContain("Full bed liner");
    expect(html).toContain("Cargo net");
    expect(html).not.toContain("None / open bed");
    expect(html).toContain("Unknown");
    expect(html).toContain("Rough monthly fuel / gas savings");
    expect(html).toContain("Annual savings");
    expect(html).not.toContain("Break-even");
    expect(html).not.toContain("break-even");
    expect(html).toContain("Home, shop, or daytime charging");
    expect(html).toContain("Workday Fit");
    expect(html).toContain("Driving energy");
    expect(html).toContain("Equipment energy");
    expect(html).toContain("End-of-day reserve");
    expect(html).toContain("Load penalty");
    expect(html).toContain("Real-world range");
    expect(html).toContain("How load hits range");
    expect(html).toContain('role="radiogroup"');
    expect(html).toContain("Battery Pack");
    expect(html).toContain("Assumptions and limitations");
    expect(html).toContain("Same workday, other trucks");
    expect(html).toContain("My current truck");
    expect(html).toContain("Shop home chargers");
    expect(html).toContain("Clear all");
    expect(html).toContain("Clear all kit selections");
    expect(html).toContain("Refresh results");
    expect(html).not.toContain("Can an EV Handle Me?");
    expect(html).toContain("When this is not a good fit");
    expect(html).toContain("That&#x27;s the demo estimate");
    expect(html).toContain('alt="2022 Rivian R1T"');
    expect(html).toContain("commons.wikimedia.org/wiki/Special:FilePath");
    expect(html).toContain("2022_Rivian_R1T_Adventure");
    expect(html).not.toContain("vehicles/r1t-2022.webp");
    expect(html).not.toContain("Illustrated build preview");
    expect(html).not.toContain("OUTFITTED BED");
  });
});
